spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/banbeiserp
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  jpa:
    show-sql: true
  liquibase:
    change-log: db/master.xml
    enabled: true